### ISSUE TITLE
Preferences is not shown.

### ISSUE THREAD

**Issue by malipetek** [staff0rd/hain-plugin-keywords#2]
I have lately installed **"keywords"** plugin, right after I have installed **"shortcuts"** plugin. But in the preferences I have this:
![sc](https://cloud.githubusercontent.com/assets/13527277/19145633/7c6be5f6-8bb8-11e6-8fe7-1e41e1c31486.PNG)

Should I have **"shortcuts"** plugin bf I install this one or should I uninst that? 
Or am I having this issue cuz hpm is experimental?

**Comment by staff0rd** [comment]
Yeah that's pretty strange, you should be able to see a separate preferences screen specific to hain-plugin-keywords.  That you don't makes me think it's not installed.  I'll try installing on another machine and see if I can get the same results.

**Comment by malipetek** [comment]
I may fork-sync my local file for your inspection as well.

**Comment by staff0rd** [comment]
Looks like the plugin was not actually loading due to a dependency (that was availble in my dev environment but not in production).  I have resolved this with version 1.0.3 of the plugin.  Thanks for pointing this out!

**Comment by malipetek** [comment]
![sc](https://cloud.githubusercontent.com/assets/13527277/19210554/b8196354-8d2e-11e6-8830-e13a420df1de.PNG)
